### ISSUE TITLE
Scroll issue with iphone4

### ISSUE THREAD

**Issue by crimsonpixel** [d0n601/drinkingAge#2]
Hi there - I've had feedback from my client who is saying the age gateway doesn't scroll in iphone4 using safari.  I don't have an iphone4 to check with but wonder if you have had any other comments / isssues.

Thanks

**Comment by d0n601** [comment]
I updated the style sheet in the repo last week to fix the appearance on mobile devices [20d994f](https://github.com/d0n601/drinkingAge/commit/20d994f088309314974f18abaa0ab0388586b442). It might not be a safari specific issue?

Does your style sheet include this media query,

`@media(max-width:768px) {
    #age_controls {
        margin:0;
        width:100%;
        height:100%;
    }`

**Comment by crimsonpixel** [comment]
Had amended the stylesheet myself but didn't put in height: 100% - will await the clients response on that one.

**Comment by d0n601** [comment]
Bouncer.js will set the overflow to hidden if the age_verification cookie is not found
[Line:39](https://github.com/d0n601/drinkingAge/blob/master/bouncer.js#L39)`$('html,body').css('overflow','hidden');`

If you'd like to be able to scroll through the site while the gateway is poped up you can remove that line. I found it was more simple to implement the height 100% to make sure it fits within the screen but doesn't allow people to scroll around the site without first going through the gateway.

**Comment by crimsonpixel** [comment]
No I'd rather leave the pop up in place.  I haven't had any further feedback, but appreciate your input.
